#define SYSTICK_TICKS_PER_SECONDS 100
#define SYSTICK_TICKS_PERIOD 10

#define INTERNAL_WATCHDOG
#define EXTERNAL_WATCHDOG

#define SW_VER "EA05"
#define SW_DATE "06042022"

extern uint32_t master_time;
